<?php
require_once('classes/Menu.php');
require_once('classes/Page.php');
require_once('classes/Database.php');
require_once('classes/Contact.php');
require_once('classes/Gallery.php');
require_once('classes/Question.php');
require_once('classes/User.php');
session_start();
?>